name: next_trip
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  table_calendar: ^3.1.3
  cloud_firestore: ^6.0.1
  datetime_picker_formfield_new: 2.1.0
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
